### ISSUE TITLE
Single js for use in HTML.

### ISSUE THREAD

**Issue by MariasStory** [alexhorn/defendjs#1]
Can you please combine the scripts in a single js and give some examples how to use the script in HTML.

**Comment by alexhorn** [comment]
I think there's a misunderstanding as to how defendjs is supposed to be used. You have to run it in Node.js as described in [the README](https://github.com/alexhorn/defendjs#usage). The resulting file can then be embedded in your HTML page.

**Comment by MariasStory** [comment]
Hi @alexhorn, thanks for your comment. Why can't defendjs be used in browser? Let's say to obfuscate some simple js code.

**Comment by alexhorn** [comment]
It was designed to be used in Node.js. You could probably rewrite it to run in a browser, but I'm not planning to do that anytime soon.
